### ISSUE TITLE
Develop branch ain't working

### ISSUE THREAD

**Issue by Ralle001** [intere/GeoTrackKit#32]
Can't install the pod.

Analyzing dependencies
Pre-downloading: `GeoTrackKit` from `git@github.com:intere/GeoTrackKit.git`, branch `develop`

[!] Error installing GeoTrackKit
[!] Failed to download 'GeoTrackKit': [!] /usr/bin/git clone git@github.com:intere/GeoTrackKit.git /var/folders/xy/0whx_ft91kdbg_1sx16ddc0w0000gp/T/d20200816-3431-h2v9wi --template= --single-branch --depth 1 --branch develop

Cloning into '/var/folders/xy/0whx_ft91kdbg_1sx16ddc0w0000gp/T/d20200816-3431-h2v9wi'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Ralle001** [comment]
@intere

**Comment by intere** [comment]
You don't have SSH set up for github.  Try using https instead:

`git clone https://github.com/intere/GeoTrackKit.git`

**Comment by Ralle001** [comment]
And how should I add it like a pod to my swift project?

**Comment by intere** [comment]
@Ralle001 - do you not know how cocoapods works?  I'd recommend starting here: https://guides.cocoapods.org/using/using-cocoapods.html

I'm not available to teach you how to use cocoapods.  There are lots of resources for this available.  If you have specific issues you're having with this library with respect to cocoapods, please feel free to open an issue.

**Comment by Ralle001** [comment]
I know but I used the one in the ReadMe file and it wasn't working. When I imported through the develop branch it worked but now it shows the error what I linked. Also when I import like the 'pod GeoTrackKit' then he code is not working.

**Comment by intere** [comment]
> You don't have SSH set up for github. Try using https instead:
> 
> `git clone https://github.com/intere/GeoTrackKit.git`

☝️ You don't have SSH configured for github, you need to use an https url, not ssh.  You need to read up on cocoapods.
